#pragma once

enum Messages {
	MSG_UNSUPPORTED_FILE_FROMAT,
	MSG_FILE_NOT_FOUND,
	MSG_MISSING_FILEPATH,
	MSG_MISSING_FILEPATH_ARGUMENT,
	MSG_UNKNOWN_FLAG,
	MSG_UNABLE_TO_WRITE,
	MSG_UNABLE_TO_READ,
	MSG_UNABLE_TO_ENCODE,
	MSG_UNABLE_TO_DECODE
};